INDEX_ERROR = 'list index out of range'
ZERO_DIVISION = 'float division by zero'
FILE_NOT_FOUND = 'file not found'
INPUT_FILE1 = 'input1.txt'
INPUT_FILE2 = 'input2.txt'
OUTPUT_FILE = 'output.txt'
